dates:
  start: '2019-10-25 00:00:00'
  end: '2019-11-05 00:00:00'
timestep: 12 # in hours

# Arkansas River near Haskell, OK
# Using pkq_site.rds file from https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/OklahomaFloods-2019/1_fetch/out/
# Plus cross-checking with NWS forecast table: nws.noaa.gov/oh/hads/USGS/[STATE ABBR]_USGS-HADS_SITES.txt
nws_site: "MTGN4"
nwis_site: "01438500"

# Should create more elegant way to get min/max stage in the future
stage:
  min: 0
  max: 15

# animation options
animation:
  frame_rate: 4 #original input frames per second
  output_frame_rate: 9 #fps, but the actual frames in the video (not 1:1 with input)
